name: Test GitHub Secrets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-secrets:
    environment: production
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Run script with secret
      env:
        SECRET_MESSAGE: ${{ secrets.SECRET_MESSAGE }}
      run: node index.js 